apiVersion: v1
kind: ConfigMap
metadata:
  name: mqsc-setting
data:
  qminit.mqsc: |
    DEFINE QLOCAL('MVP.NEW.ORDERS.Q') REPLACE
    DEFINE QLOCAL('MVP.DEAD.LETTER.QUEUE') REPLACE
    ALTER QMGR DEADQ('MVP.DEAD.LETTER.QUEUE')
    DEFINE CHANNEL('MVP.APP.SVRCONN') CHLTYPE(SVRCONN) MCAUSER('mqm') REPLACE
    DEFINE CHANNEL('MVP.INSTANA.SVRCONN') CHLTYPE(SVRCONN) MCAUSER('mqm') REPLACE
    ALTER QMGR ACCTMQI(ON) ACCTQ(ON) MONCHL(MEDIUM) MONQ(MEDIUM) STATCHL(MEDIUM) STATMQI(ON) STATQ(ON)
    ALTER QMGR CONNAUTH('') CHLAUTH(DISABLE)
    REFRESH SECURITY(*) TYPE(CONNAUTH)
