apiVersion: v1
kind: ConfigMap
metadata:
  name: mqsc-setting
data:
  qminit.mqsc: |
    DEFINE QLOCAL('MVP.NEW.ORDERS.Q') DEFPSIST(YES) REPLACE
    ALTER QMGR DEADQ('MVP.NEW.ORDERS.Q')
    ALTER QMGR CONNAUTH('') CHLAUTH(DISABLED)
    REFRESH SECURITY(*) TYPE(CONNAUTH)
    DEFINE CHANNEL('MVP.APP.SVRCONN') CHLTYPE(SVRCONN) MCAUSER('mqm') REPLACE
