apiVersion: v1
kind: ConfigMap
metadata:
  name: mqsc-setting
data:
  qminit.mqsc: |
    DEFINE CHANNEL('MVP.APP.CHANNEL') CHLTYPE(SVRCONN) MCAUSER('mqm') REPLACE
    DEFINE CHANNEL('MVP.APP.1') CHLTYPE(SVRCONN) MCAUSER('mqm') REPLACE
    DEFINE QLOCAL(APP.EVENTS.QUEUE) MAXDEPTH(100) REPLACE
    DEFINE QLOCAL(APP.QUEUE) STRMQOS(MUSTDUP) STREAMQ(APP.EVENTS.QUEUE) MAXDEPTH(100) REPLACE
    ALTER QMGR ACCTMQI(ON) ACCTQ(ON) MONCHL(MEDIUM) MONQ(MEDIUM) STATCHL(MEDIUM) STATMQI(ON) STATQ(ON)
    ALTER QMGR CHLAUTH (DISABLED)
    REFRESH SECURITY
