apiVersion: v1
kind: ConfigMap
metadata:
  name: mqsc-setting
data:
  qminit.mqsc: |
    DEFINE QLOCAL('MVP.NEW.ORDERS.Q') DEFPSIST(YES) REPLACE
    DEFINE QLOCAL('MVP.DEAD.LETTER.QUEUE') DEFPSIST(YES) REPLACE
    ALTER QMGR DEADQ('MVP.DEAD.LETTER.QUEUE')
    ALTER QLOCAL('MVP.NEW.ORDERS.Q') MONQ(LOW) 
    ALTER QMGR MONQ(LOW)
    ALTER QMGR CONNAUTH('') CHLAUTH(DISABLED)
    ALTER QMGR PERFMEV(ENABLED) CHLEV(ENABLED)
    REFRESH SECURITY(*) TYPE(CONNAUTH)
    DEFINE CHANNEL('MVP.APP.SVRCONN') CHLTYPE(SVRCONN) MCAUSER('mqm') REPLACE
