apiVersion: v1
kind: ConfigMap
metadata:
  name: mqsc-setting
data:
  qminit.mqsc: |
    DEFINE QLOCAL('MVP.NEW.ORDERS.Q') DEFPSIST(YES) REPLACE
    DEFINE QLOCAL('MVP.DEAD.LETTER.QUEUE') DEFPSIST(YES) REPLACE
    ALTER QMGR DEADQ('MVP.DEAD.LETTER.QUEUE')
    ALTER QLOCAL('MVP.NEW.ORDERS.Q') MONQ(LOW) 
    ALTER QMGR MONQ(LOW)
    ALTER QMGR PERFMEV(ENABLED) CHLEV(ENABLED)
    DEFINE CHANNEL('MVP.APP.SVRCONN') CHLTYPE(SVRCONN) MCAUSER('mqm') REPLACE
    
    SET AUTHREC OBJTYPE(QMGR) GROUP('mqadmins') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('**') GROUP('mqadmins') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(CHANNEL) PROFILE('**') GROUP('mqadmins') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(TOPIC) PROFILE('**') GROUP('mqadmins') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(LISTENER) PROFILE('**') GROUP('mqadmins') AUTHADD(ALL)
    
    SET CHLAUTH('INSTANA.CHANNEL') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(CHANNEL) CHCKCLNT(REQUIRED) DESCR('Allows connection via INSTANA channel') ACTION(REPLACE)
    DEFINE CHANNEL(INSTANA.CHANNEL) CHLTYPE(SVRCONN)
        
    ALTER QMGR CONNAUTH('') CHLAUTH(DISABLED)
    REFRESH SECURITY(*) TYPE(CONNAUTH)
