apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm-prod
spec:
  license:
    accept: true
    license: L-RJON-BZFQU2
    use: Production
  queueManager:
    mqsc:
    - configMap:
        items:
        - qminit.mqsc
        name: mqsc-setting
    name: QM_MVP
    availability:
      type: NativeHA
  version: 9.2.3.0-r1
  web:
    enabled: true
