apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm-mvp
spec:
  license:
    accept: true
    license: L-RJON-BUVMQX
    use: NonProduction
  web:
    enabled: true
  version: 9.2.3.0-r1
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  queueManager:
    mqsc:
    - configMap:
        items:
        - qminit.mqsc
        name: mqsc-setting
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    name: MVP_QUICKSTART
    availability:
      type: NativeHA
    storage:
      defaultClass: ocs-storagecluster-ceph-rbd
      persistedData:
        class: ocs-storagecluster-ceph-rbd
        enabled: true
        size: 1Gi
        type: persistent-claim
      queueManager:
        class: ocs-storagecluster-ceph-rbd
        size: 1Gi
        type: persistent-claim
      recoveryLogs:
        class: ocs-storagecluster-ceph-rbd
        enabled: true
        size: 1Gi
        type: persistent-claim
