apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  annotations:
    com.ibm.mq/write-defaults-spec: 'false'
  name: qm1
  namespace: fab-mq-demo
spec:
  license:
    accept: true
    license: L-QYVA-B365MB
    use: NonProduction
  queueManager:
    name: QM1
    mqsc:
    - configMap:
        items:
        - qm.mqsc
        name: mqsc-setting
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    storage:
      queueManager:
        type: persistent-claim
      defaultClass: ocs-storagecluster-ceph-rbd
    availability:
      type: NativeHA
  version: 9.4.2.0-r1
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true
