apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm2
  labels:
    app: new-orders-service
    environment: mvp
spec:
  license:
    accept: true
    license: L-RJON-CJR2RX
    use: NonProduction
  web:
    enabled: true
  telemetry:
    tracing:
      instana:
        enabled: true
  version: 9.3.2.1-r1
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  queueManager:
    mqsc:
    - configMap:
        items:
        - qm.mqsc
        name: mqsc-setting
    resources:
      limits:
        cpu: 300m
      requests:
        cpu: 100m
    name: QM1
    availability:
      type: NativeHA
    storage:
      defaultClass: ibmc-block-gold
      persistedData:
        class: ibmc-block-gold
        enabled: true
        size: 1Gi
        type: persistent-claim
      queueManager:
        class: ibmc-block-gold
        size: 1Gi
        type: persistent-claim
      recoveryLogs:
        class: ibmc-block-gold
        enabled: true
        size: 1Gi
        type: persistent-claim
