apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm-prod
spec:
  license:
    accept: true
    license: L-RJON-BUVMQX
    use: Production
  queueManager:
    mqsc:
    - configMap:
        items:
        - qminit.mqsc
        name: mqsc-setting
    name: QMMVP
    availability:
      type: NativeHA
  version: 9.2.3.0-r1
  web:
    enabled: true
  storage:
      defaultClass: ocs-storagecluster-ceph-rbd
      persistedData:
        enabled: false
      queueManager:
        class: ocs-storagecluster-ceph-rbd
        size: 2Gi
        type: persistent-claim
      recoveryLogs:
        enabled: false
